### ISSUE TITLE
Module Documentation Tracking Issue

### ISSUE THREAD

**Issue by bhgomes** [Manta-Network/manta-rs#21]
We need to add documentation for each of these modules. To check off one of these boxes, add a link to the PR that fills in the documentation. If one of these boxes should be checked off without a PR that fills it in, leave a comment below explaining why.
- [ ] `manta-util`
    - [ ] `array`
    - [ ] `bytes`
    - [ ] `cache`
    - [ ] `codec`
    - [ ] `convert`
    - [ ]  `iter`
    - [ ] `num`
    - [ ] `persistence`
    - [ ] `pointer`
    - [ ] `sealed`
- [ ] `manta-crypto`
    - [ ] `accumulator`
    - [ ] `commitment`
    - [ ] `constraint`
    - [ ] `ecc`
    - [ ] `encryption`
    - [ ] `hash`
    - [ ] `key`
    - [ ] `merkle_tree`
        - [ ] `forest`
        - [ ] `fork`
        - [ ] `full`
        - [ ] `inner_tree`
        - [ ] `node`
        - [ ] `partial`
        - [ ] `path`
        - [ ] `single_path`
        - [ ] `test`
        - [ ] `tree`
    - [ ] `rand`
- [ ] `manta-accounting`
    - [ ] `asset`
    - [ ] `fs`
        - [ ] `serde`
    - [ ] `key`
    - [ ] `transfer`
        - [ ] `batch`
        - [ ] `canonical`
        - [ ] `test`
    - [ ] `wallet`
        - [ ] `ledger`
        - [ ] `signer`
        - [ ] `state`
        - [ ] `test`
            - [ ] `sim`
- [ ] `manta-pay`
    - [ ] `bin`
        - [ ] `generate_parameters`
        - [ ] `simulation`
    - [ ] `config`
    - [ ] `crypto`
        - [ ] `constraint`
            - [ ] `arkworks`
                - [ ] `codec`
                - [ ] `groth16`
                - [ ] `pairing`
            - [ ] `plonk`
        - [ ] `ecc`
            - [ ] `arkworks`
        - [ ] `encryption`
        - [ ] `hash`
            - [ ] `poseidon`
        - [ ] `key`
    - [ ] `key`
    - [ ] `signer`
        - [ ] `base`
        - [ ] `client`
            - [ ] `http`
            - [ ] `websocket`
    - [ ] `simulation`
    - [ ] `test`
        - [ ] `transfer`

**Comment by akshad113** [comment]
hello I am new to open source can you show me the way.
