### ISSUE TITLE
Use Fastest Poseidon Implementation

### ISSUE THREAD

**Issue by bhgomes** [Manta-Network/manta-rs#22]
We have a few different Poseidon implementations in the Manta ecosystem and we want to use the fastest one in production. Here are some goals for merging the implementation from [Plonk-Prototype](https://github.com/manta-network/Plonk-Prototype):

- Upgrade `posiedon` file to directory in `manta-pay` crate
- Keep the same interface that is defined in the current `poseidon` module, just upgrade the implementation (should not need to change any other files in `manta-pay` after the upgrade)
- Add tests for consistency with known Poseidon implementations
- Add in the parameter generation logic into the `posiedon` module and upgrade the parameters in the `bin/generate_parameters.rs` file (also remove the `Sample` implementation since it is not correct)
- Add a PR to [manta-sdk](https://github.com/manta-network/sdk) for new parameters

NB: For this PR we only care about the R1CS implementation, not PLONK.

**Comment by tsunrise** [comment]
I will start this soon
