### ISSUE TITLE
Use Pre-computed Powers in Scalar Multiplication

### ISSUE THREAD

**Issue by bhgomes** [Manta-Network/manta-rs#24]
Right now we use a slow kind of scalar multiplication in-circuit where we compute powers of the base while multiplying. We can pre-compute these powers before entering the circuit and save on a lot of constraints. We can leverage the `PrecomputedScalarMul` trait and the other traits in `manta_crypto::ecc` to do this.

Since this is a parameter change, we need to make sure to upgrade the SDK whenever we add this in.

**Comment by tsunrise** [comment]
What's the purpopse of `PreprocessedScalarMul` in current codebase?

**Comment by SupremoUGH** [comment]
https://github.com/Manta-Network/manta-rs/pull/196 closes this. The corresponding trait is `FixedBaseScalarMul`.
