### ISSUE TITLE
Add poseidon reference implementation (using sage)

### ISSUE THREAD

**Issue by tsunrise** [Manta-Network/manta-rs#67]
After #57 is merged, we might consider adding some sage scripts as a reference implementation to make sure the implementation is correct. 

_Originally posted by @BoyuanFeng in https://github.com/Manta-Network/manta-rs/pull/57#discussion_r869376550_

**Comment by SupremoUGH** [comment]
Closed. Poseidon consists of multiple rounds, split into full and partial rounds. The hardcoded test for those (albeit not generated by a sage script) is done in `constants.rs` in
- https://github.com/Manta-Network/manta-rs/pull/57

Each round consists of three steps, namely: 
- Add round constants, whose hardcoded values test given by `parameters_hardcoded_test/lfsr_values` is done in https://github.com/Manta-Network/manta-rs/pull/206
- Permutation, whose test given by `permutation_hardcoded_test/width3` is done in https://github.com/Manta-Network/manta-rs/pull/168
- MDS Matrices, whose test given by `mds_hardcoded_tests/width*n*` is done in https://github.com/Manta-Network/manta-rs/pull/149.
