### ISSUE TITLE
Move Posiedon Sage Script Here

### ISSUE THREAD

**Issue by bhgomes** [Manta-Network/manta-rs#84]
We want to move this script (https://github.com/Manta-Network/Plonk-Prototype/tree/poseidon_hash_clean) into the relevant place for the latest Poseidon impl.

**Comment by tsunrise** [comment]
Make sure to move both scripts:
* [generate_parameters_grain_deterministic.sage](https://github.com/Manta-Network/Plonk-Prototype/blob/poseidon_hash_clean/generate_parameters_grain_deterministic.sage) is used to for hardcoded tests in https://github.com/Manta-Network/manta-rs/pull/57/files#diff-a930a23782f66c505a6f84e4ba0f9a1868904d4525cfe73fe9cd3ff825c79c13R78-R109
* [poseidonperm_bls381_width3.sage](https://github.com/Manta-Network/Plonk-Prototype/blob/poseidon_hash_clean/poseidonperm_bls381_width3.sage) is used for hardcoded tests for poseidon hash (indeed I cannot find such test in #57)
