### ISSUE TITLE
Setup Poseidon as a Permutation

### ISSUE THREAD

**Issue by bhgomes** [Manta-Network/manta-rs#99]
To integrate Poseidon in the duplex-sponge encryption circuits, we want to add it as an instance of `PseudorandomPermutation` (see https://github.com/Manta-Network/manta-rs/pull/81 for definition). To do this we need at least the following interfaces:

```rust
impl manta_crypto::permutation::PseudorandomPermutation for Poseidon {}
impl manta_crypto::permutation::sponge::Absorb for Input {}
impl manta_crypto::permutation::sponge::Squeeze for Output {}
```

where `Input` and `Output` are constrained to be `ARITY`-long vectors (not `WIDTH`-long since the extra state field element is the "capacity" of the sponge and we cannot read/write it). Then, for Poseidon as a hash function, we should simply implement `ArrayHashFunction` as usual which will execute the `PseudorandomPermutation` impl and then project out the `0`-th component.

**Comment by tsunrise** [comment]
@bhgomes Any open PR linked to this issue?

**Comment by bhgomes** [comment]
> @bhgomes Any open PR linked to this issue?

I'm setting it up in an hour or so, just want to merge these in the correct order.
